- name: Configure the DHCP server
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcpd.conf
  become: true
  notify: restart dhcpd
- name: Enable dhcpd
  lineinfile:
    path: /etc/rc.conf
    regexp: '^dhcpd='
    line: 'dhcpd=YES'
  become: true
  notify: restart dhcpd
- name: Start dhcpd
  service:
    name: dhcpd
    state: started
  become: true
